
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

#url: "https://mariacamilarg.github.io"
url: "https://mariacamilarg.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: / # for deployment
#baseurl: /mariacamilarg # for dev


# Google tracking id

google-tracking-id: "UA-86315464-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Maria Camila Remolina Gutiérrez"
title: "MARIA CAMILA REMOLINA GUTIÉRREZ"
description: "Personal website of Maria Camila Remolina Gutiérrez."
keywords: "astronomy, programming, personal, remolina-gutierrez, maria, camila"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"
background-img: "../img/wallpaper_blurry.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Sometimes it is the people no one can imagine anything of who do the things no one can imagine. - Alan Turing"
  - text: "It is the time you have wasted for your rose that makes your rose so important. - Antoine de Saint-Exupéry"
  - text: "We are a way for the universe to know itself. - Carl Sagan"
  - text: "Some infinities are bigger than other infinities. - John Green"
  - text: "We adore chaos because we love to produce order. - M. C. Escher"

# To use local profile pic uncomment the following line
# me-img: "/img/me.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.
me-img: "https://github.com/mariacamilarg.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.
# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: False
pinterest-share: False
pocket-share: True
vkontakte-share: False

#disqus-shortname: "mariacamilarg"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/coding.jpg"
    date: "June 2011"
    description: "Started coding"
  - image: "/img/timeline/highschool.jpg"
    date: "December 2011"
    description: "Graduated from High School"
  - image: "/img/timeline/uniandes.jpg"
    date: "Mar 2017 / Jul 2018"
    description: "Graduated from Uniandes as a Physicist & Engineer"
  - image: "/img/timeline/parissaclay.png"
    date: "Aug 2018 - Today"
    description: "Started master in Computer Science in Paris, France"

# First image of the Timeline

timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "mariacamilaremolinagutierrez@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Maria Camila is in love with learning, traveling, living new experiences and meeting new friends. She doesn't like trying new food tho, but she compensates it in ice-cream eating!"
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/mariacamilarg"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/mariacamilarg/"
  - title: "twitter"
    url: "https://twitter.com/holamariacamila"

############
# 404 page #
############

err-404-img: "/img/404.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  More: 'more'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

# Plugins

plugins:
  - jekyll-paginate
  - jemoji
